//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class approveflow
    {
        public int id { get; set; }
        public int status { get; set; }
        public Nullable<int> type { get; set; }
        public string PC_email { get; set; }
        public string BOI_email { get; set; }
        public string PD_email { get; set; }
        public string SAFETY_email { get; set; }
        public string GAAC_email { get; set; }
        public string DIR_email { get; set; }
        public string GA_email { get; set; }
    }
}
