//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int id { get; set; }
        public string approver_id { get; set; }
        public string approver_name { get; set; }
        public string approver_email { get; set; }
        public string approver_department { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public string doc_no { get; set; }
    
        public virtual heading heading { get; set; }
    }
}
