//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class detail_pass
    {
        public int item_no { get; set; }
        public string doc_no { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public string purpose { get; set; }
        public string invoice_no { get; set; }
        public string image_url { get; set; }
        public byte[] image_data { get; set; }
    
        public virtual heading heading { get; set; }
    }
}
