//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class heading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public heading()
        {
            this.approvals = new HashSet<approval>();
            this.detail_pass = new HashSet<detail_pass>();
        }
    
        public string doc_no { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public Nullable<int> tel_no { get; set; }
        public string vec_no { get; set; }
        public Nullable<System.TimeSpan> time_out { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string requester { get; set; }
        public string department { get; set; }
        public Nullable<int> requester_tel { get; set; }
        public string manager { get; set; }
        public string dgm { get; set; }
        public string security { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> status { get; set; }
        public int formtype { get; set; }
        public string factory { get; set; }
        public Nullable<int> type { get; set; }
        public string asset_no { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string checked_by { get; set; }
        public Nullable<int> checkin_status { get; set; }
        public Nullable<int> checkout_status { get; set; }
        public Nullable<System.DateTime> checkin_date { get; set; }
        public Nullable<System.DateTime> checkout_date { get; set; }
        public Nullable<int> warehouse_check { get; set; }
        public Nullable<System.DateTime> warehouse_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval> approvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_pass> detail_pass { get; set; }
    }
}
