//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string role { get; set; }
        public string factory { get; set; }
        public string department { get; set; }
        public string email { get; set; }
    }
}
