//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gatepass_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gatepassEntities : DbContext
    {
        public gatepassEntities()
            : base("name=gatepassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detail_pass> detail_pass { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<approval> approvals { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<heading> headings { get; set; }
        public virtual DbSet<approveflow> approveflows { get; set; }
    }
}
